name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  rgbds_version: v1.0.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Checkout rgbds
        uses: actions/checkout@v6
        with:
          path: rgbds
          ref: ${{ env.rgbds_version }}
          repository: gbdev/rgbds

      - name: Install rgbds
        working-directory: rgbds
        run: |
          sudo apt-get update
          sudo apt-get install -yq bison libpng-dev pkg-config
          sudo make -j$(nproc) install

      - name: Remove rgbds
        run: |
          rm -rf rgbds

      # - name: Compare
      #  if: ${{ github.repository_owner == 'pret' }}
      #  run: |
      #    make DEBUG=1 -j$(nproc) compare
      #    .github/checkdiff.sh

      - name: Make
        run: |
          make -j$(nproc)
          
      # - name: Upload Gold artifact
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: pokegold
      #    path: pokegold.gbc
          
      # - name: Upload Silver artifact
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: pokesilver
      #    path: pokesilver.gbc

      # - name: Checkout symbols
      #  if: ${{ github.repository_owner == 'pret' && github.event_name == 'push' }}
      #  uses: actions/checkout@v6
      #  with:
      #    path: symbols
      #    ref: symbols

      # - name: Move symbols
      #  if: ${{ github.repository_owner == 'pret' && github.event_name == 'push' }}
      #  run: |
      #    cp -v *.sym *.map symbols/

      # - name: Update symbols
      #  if: ${{ github.repository_owner == 'pret' && github.event_name == 'push' }}
      #  uses: EndBug/add-and-commit@v9
      #  with:
      #    cwd: "./symbols"
      #    add: "*.sym *.map"
      #    message: ${{ github.event.commits[0].message }}

  # build-macos:
  #  runs-on: macos-latest
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v6

  #    - name: Checkout rgbds
  #      uses: actions/checkout@v6
  #      with:
  #        path: rgbds
  #        ref: ${{ env.rgbds_version }}
  #        repository: gbdev/rgbds

  #    - name: Install rgbds
  #      working-directory: rgbds
  #      run: |
  #        brew install bison libpng pkg-config
  #        export PATH="$(brew --prefix bison)/bin:$PATH"
  #        sudo make -j$(sysctl -n hw.ncpu) install

  #    - name: Remove rgbds
  #      run: |
  #        rm -rf rgbds

  #    - name: Compare
  #      if: ${{ github.repository_owner == 'pret' }}
  #      run: |
  #        make DEBUG=1 -j$(sysctl -n hw.ncpu) compare
  #        .github/checkdiff.sh

  #    - name: Make
  #      if: ${{ github.repository_owner != 'pret' }}
  #      run: |
  #        make -j$(sysctl -n hw.ncpu)
  #        .github/checkdiff.sh
          
  validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 2
          
      - name: Get all changed asm files
        id: changed-asm-files
        uses: tj-actions/changed-files@v45.0.3
        with:
          files: |
            **.asm
        
      - name: Install Mono
        if: steps.changed-asm-files.outputs.any_changed == 'true'
        run: |
          sudo apt install ca-certificates gnupg
          sudo gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/mono-official-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
          echo "deb [signed-by=/usr/share/keyrings/mono-official-archive-keyring.gpg] https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
          sudo apt update
          sudo apt install mono-complete
          
      - name: Compile validator
        if: steps.changed-asm-files.outputs.any_changed == 'true'
        run: |
          sudo chmod +x tools/PokeGen2TextValidator.cs
          mcs -out:tools/PokeGen2TextValidator.exe tools/PokeGen2TextValidator.cs
            
      - name: Validate
        if: steps.changed-asm-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-asm-files.outputs.all_changed_files }}
        run: |
          PROBLEM=0
          set +e
          for file in ${ALL_CHANGED_FILES}; do
            trap 'PROBLEM=1' ERR
            mono tools/PokeGen2TextValidator.exe $file
          done
          set -e
          exit $PROBLEM